name: hs-blog # you probably want to 'snapcraft register <name>'
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: hs-blog webapp # 79 char long summary
description: |
  This is webapp version of my blog.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  hs-blog:
    command: webapp-launcher --enable-back-forward --webappUrlPatterns=http?://www.hanandjun.com/* http://www.hanandjun.com/ %u
    plugs:
      - browser-sandbox
      - camera
      - network
      - network-bind
      - opengl
      - pulseaudio
      - screen-inhibit-control
      - unity7
      - network-control
      - mount-observe

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: false
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  webapp-container:
    after: [desktop-ubuntu-app-platform,webapp-helper]
    stage-packages:
      - fonts-wqy-zenhei
      - fcitx-frontend-qt5
    plugin: nil
